/* UI, cameras, accessibility, touch controls and offline persistence. */
TR.App=class{
 constructor(){
 this.$=id=>document.getElementById(id);this.saved=TR.Store.load();this.settings={auto:true,sound:true,music:false,quality:1,weather:'sunset',car:'gt',...this.saved.settings};if(!TR.CARS[this.settings.car])this.settings.car='gt';this.mode='rush';this.car=this.settings.car;this.keys=new Set();this.pointers=new Map();this.touch={};this.cameraMode=0;this.time=0;this.bannerUntil=0;this.toastUntil=0;this.tutorialDismissed=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.audio=new TR.Audio();this.audio.enabled=this.settings.sound;this.audio.music=this.settings.music;try{this.R=new TR.Renderer(this.$('world'));}catch(webglError){let old=this.$('world'),fresh=old.cloneNode(false);old.replaceWith(fresh);this.R=new TR.CanvasRenderer(fresh);this.software=true;this.settings.quality=0;}this.R.quality=this.settings.quality===0?0:1;this.R.resize();this.route=new TR.Route();this.world=new TR.World(this.R,this.route);this.game=new TR.Simulation(this.route);this.game.onEvent=e=>this.event(e);this.cameraEye=null;this.cameraTarget=null;this.fx=this.$('fx').getContext('2d');this.lastUI=0;this.lastMap=0;this.lastTime=performance.now();this.accumulator=0;this.initialized=true;this.bind();this.resize();this.selectCar(this.car);this.selectMode('rush');this.syncSettings();this.showMenu();this.$('loading').hidden=true;this.$('routeLength').textContent=(this.route.length/1000).toFixed(1)+' KM';this.drawMap(this.$('menuMap'),true);this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);
 if(new URLSearchParams(location.search).has('test')){window.__THANE_TEST__={app:this,step:(seconds,input={throttle:true})=>{for(let i=0;i<seconds*120;i++)this.game.step(1/120,input);this.updateHUD();return this.snapshot();},snapshot:()=>this.snapshot(),teleport:(s,x=-1.65,speed=35)=>{this.game.s=s;this.game.x=x;this.game.speed=speed;this.game.zone=this.route.zone(s);this.cameraEye=null;return this.snapshot();}};}
 }
 snapshot(){let g=this.game;return{state:g.state,mode:g.mode,car:g.car,s:g.s,x:g.x,speed:g.speed,nitro:g.nitro,time:g.time,remaining:g.remaining,score:g.score,collisions:g.collisions,pickups:g.pickups,position:g.position(),zone:g.zone,routeLength:this.route.length,drawCalls:this.R.drawCalls,result:g.result};}
 saveSettings(){this.saved.settings=this.settings;TR.Store.save(this.saved);}
 weather(){return this.mode==='monsoon'?'rain':this.settings.weather==='night'?'night':'sunset';}
 syncSettings(){this.$('touchGas').hidden=this.settings.auto;this.$('soundState').textContent=this.settings.sound?'ON':'OFF';this.$('autoButton').innerHTML='AUTO THROTTLE <b>'+(this.settings.auto?'ON':'OFF')+'</b><kbd>T</kbd>';this.$('pauseAuto').innerHTML='AUTO THROTTLE <b>'+(this.settings.auto?'ON':'OFF')+'</b>';this.$('musicButton').innerHTML='MUSIC <b>'+(this.settings.music?'ON':'OFF')+'</b>';this.$('qualityButton').innerHTML='GRAPHICS <b>'+(this.settings.quality?'HIGH':'LITE')+'</b>';let cam=this.cameraMode?'ROAD':'CHASE';this.$('cameraButton').innerHTML=cam+' CAM<kbd>C</kbd>';this.$('pauseCam').innerHTML='CAMERA <b>'+cam+'</b>';this.$('weatherButton').innerHTML=this.weather()==='rain'?'☂<small>RAIN</small>':this.weather()==='night'?'☾<small>NIGHT</small>':'☀<small>DUSK</small>';this.audio.enabled=this.settings.sound;this.audio.music=this.settings.music;this.$('audioButton').setAttribute('aria-pressed',String(this.settings.sound));}
 selectMode(mode){this.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>{let yes=b.dataset.mode===mode;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});this.$('modeHint').textContent=mode==='free'?'ENDLESS CRUISE · NO PRESSURE':mode==='monsoon'?'WET GRIP · HEAVY TRAFFIC':'3 RIVALS · CHECKPOINT RACE';this.$('weatherButton').disabled=mode==='monsoon';this.syncSettings();}
 selectCar(car){this.car=car;this.settings.car=car;document.querySelectorAll('[data-car]').forEach(b=>{let yes=b.dataset.car===car;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});this.$('carHint').textContent=TR.CARS[car].tag;this.saveSettings();}
 clearInput(){this.keys.clear();this.pointers.clear();this.touch={};document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));}
 showMenu(){this.game.state='menu';this.clearInput();document.body.dataset.screen='menu';for(let id of['hud','pauseOverlay','resultsOverlay','infoOverlay'])this.$(id).hidden=true;this.$('menu').hidden=false;this.cameraEye=null;this.cameraMode=0;this.audio.update(this.game);this.drawMap(this.$('menuMap'),true);this.syncSettings();}
 start(){this.clearInput();this.audio.init();this.audio.enabled=this.settings.sound;this.game.reset(this.mode,this.car);this.cameraEye=null;this.cameraTarget=null;this.cameraMode=0;this.tutorialDismissed=false;this.bannerUntil=0;this.$('checkpointBanner').classList.remove('show');this.$('toast').classList.remove('show');this.$('tutorial').hidden=false;this.$('tutorial').querySelector('span').textContent=matchMedia('(pointer:coarse)').matches?'Hold the arrows to steer. Hold ϟ to boost; BRAKE before a tight bend.':'Steer with A / D or ← / →. Hold SPACE for a little extra chaos.';this.$('tutorial').firstChild.textContent=this.settings.auto?'AUTO THROTTLE IS ON ':matchMedia('(pointer:coarse)').matches?'MANUAL THROTTLE · HOLD GAS ':'MANUAL THROTTLE · HOLD W OR ↑ ';for(let id of['menu','pauseOverlay','resultsOverlay','infoOverlay'])this.$(id).hidden=true;this.$('hud').hidden=false;document.body.dataset.screen='countdown';this.$('countdown').innerHTML='3<small>UPVAN IS CALLING</small>';this.updateHUD();this.syncSettings();this.$('startButton').blur();}
 togglePause(){let g=this.game;if(g.state==='paused')g.resume();else g.pause();}
 toggleAuto(){this.settings.auto=!this.settings.auto;this.syncSettings();this.saveSettings();}
 toggleAudio(){this.audio.init();this.settings.sound=!this.settings.sound;this.syncSettings();this.saveSettings();}
 toggleMusic(){this.audio.init();this.settings.music=!this.settings.music;this.syncSettings();this.saveSettings();}
 toggleCamera(){this.cameraMode=1-this.cameraMode;this.cameraEye=null;this.syncSettings();}
 async fullScreen(){try{if(!document.fullscreenElement){if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else this.toast('USE LANDSCAPE','Full screen is not supported here.');}else if(document.exitFullscreen)await document.exitFullscreen();}catch(e){this.toast('STAY IN THE BROWSER','Full screen was not available.');}}
 bind(){
 const on=(id,fn)=>this.$(id).addEventListener('click',fn);on('startButton',()=>this.start());document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>this.selectMode(b.dataset.mode)));document.querySelectorAll('[data-car]').forEach(b=>b.addEventListener('click',()=>this.selectCar(b.dataset.car)));
 on('audioButton',()=>this.toggleAudio());on('fullButton',()=>this.fullScreen());on('pauseButton',()=>this.togglePause());on('resumeButton',()=>this.game.resume());on('restartButton',()=>this.start());on('quitButton',()=>this.showMenu());on('endDriveButton',()=>this.game.finish(true));on('raceAgainButton',()=>this.start());on('garageButton',()=>this.showMenu());on('autoButton',()=>this.toggleAuto());on('pauseAuto',()=>this.toggleAuto());on('musicButton',()=>this.toggleMusic());on('cameraButton',()=>this.toggleCamera());on('pauseCam',()=>this.toggleCamera());on('hornButton',()=>this.game.horn());on('touchHorn',()=>this.game.horn());on('dismissTutorial',()=>{this.tutorialDismissed=true;this.$('tutorial').hidden=true;});on('weatherButton',()=>{this.settings.weather=this.settings.weather==='night'?'sunset':'night';this.syncSettings();this.saveSettings();});on('qualityButton',()=>{this.settings.quality=this.settings.quality?0:1;this.R.quality=this.settings.quality;this.resize();this.syncSettings();this.saveSettings();});on('homeLink',e=>{e.preventDefault();if(this.game.state==='menu')return;this.game.pause();});on('aboutButton',()=>this.openAbout());on('recordsButton',()=>this.openRecords());on('closeInfo',()=>{this.$('infoOverlay').hidden=true;this.$('startButton').focus();});on('copyButton',()=>this.copyRun());
 for(let b of document.querySelectorAll('[data-touch]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,b.dataset.touch);b.classList.add('pressed');this.refreshTouch();});const release=e=>{this.pointers.delete(e.pointerId);b.classList.remove('pressed');this.refreshTouch();};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
 window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;let code=e.code;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(code))e.preventDefault();this.keys.add(code);if(e.repeat)return;if(!this.$('infoOverlay').hidden){if(code==='Escape')this.$('infoOverlay').hidden=true;return;}if(code==='Enter'&&(this.game.state==='menu'||this.game.state==='results'))this.start();if(code==='KeyP'||code==='Escape')this.togglePause();if(code==='KeyR'&&['running','paused','results'].includes(this.game.state))this.start();if(code==='KeyH')this.game.horn();if(code==='KeyM')this.toggleAudio();if(code==='KeyN')this.toggleMusic();if(code==='KeyC')this.toggleCamera();if(code==='KeyT')this.toggleAuto();if(code==='KeyF')this.fullScreen();});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.clearInput();this.game.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.clearInput();this.game.pause();}});window.addEventListener('resize',()=>this.resize());
 this.$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();this.game.pause();this.showError('The browser paused the graphics device. Reload the game to restore it. Your saved records are safe.');});
 // Keep keyboard focus inside any currently open dialog.
 window.addEventListener('keydown',e=>{if(e.key!=='Tab')return;let overlay=['infoOverlay','resultsOverlay','pauseOverlay'].map(id=>this.$(id)).find(el=>!el.hidden);if(!overlay)return;let a=[...overlay.querySelectorAll('button:not([disabled]),a[href]')].filter(el=>el.getClientRects().length);if(!a.length)return;let first=a[0],last=a[a.length-1];if(e.shiftKey&&(document.activeElement===first||!overlay.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!overlay.contains(document.activeElement))){e.preventDefault();first.focus();}});
 }
 refreshTouch(){this.touch={};for(let action of this.pointers.values())this.touch[action]=true;}
 input(){let k=this.keys,t=this.touch;return{steer:(k.has('KeyD')||k.has('ArrowRight')||t.right?1:0)-(k.has('KeyA')||k.has('ArrowLeft')||t.left?1:0),throttle:this.settings.auto||k.has('KeyW')||k.has('ArrowUp')||t.throttle,brake:k.has('KeyS')||k.has('ArrowDown')||t.brake,boost:k.has('Space')||t.boost,drift:k.has('ShiftLeft')||k.has('ShiftRight')||t.drift};}
 event(e){let g=this.game;this.audio.event(e.type);if(e.type==='count')this.$('countdown').innerHTML=e.number+'<small>UPVAN IS CALLING</small>';if(e.type==='go'){document.body.dataset.screen='running';this.$('countdown').innerHTML='GO!<small>TAKE THE LONG WAY HOME</small>';this.goUntil=this.time+.75;}if(e.type==='pause'){document.body.dataset.screen='paused';this.$('pauseOverlay').hidden=false;this.$('endDriveButton').hidden=g.mode!=='free';this.$('quitButton').hidden=g.mode==='free';this.clearInput();this.syncSettings();this.audio.update(g);this.$('resumeButton').focus();}if(e.type==='resume'){document.body.dataset.screen=g.state;this.$('pauseOverlay').hidden=true;this.clearInput();this.$('resumeButton').blur();}if(e.type==='score')this.toast('+'+e.points,e.label+(g.combo>1?' · ×'+g.combo:''));if(e.type==='horn'&&e.count)this.toast('MAKE A LITTLE ROOM','TRAFFIC YIELDS TO YOUR HORN');if(e.type==='hit')this.toast(e.kind==='pothole'?'THAT WAS A POTHOLE.':e.kind==='barrier'?'EASY ON THE EDGES.':'A LITTLE TOO CLOSE.',e.kind==='pothole'?'−80 · THERE GOES THE CHAI':'−180 · RESET. FIND YOUR LINE.');
 if(e.type==='checkpoint'){let z=this.route.zones[e.zone];this.$('bannerKicker').textContent=g.mode==='free'?'THE SCENIC ROUTE CONTINUES':'CHECKPOINT  /  +'+e.seconds+' SECONDS';this.$('bannerTitle').textContent=z.short;this.$('bannerDetail').textContent=e.clean?'CLEAN SECTOR +500  ·  '+z.sub:z.sub;this.$('checkpointBanner').classList.add('show');this.bannerUntil=this.time+3.8;}if(e.type==='lap')this.toast('LAP '+e.lap,'THE LAKE LOOKS GOOD FROM EVERY ANGLE');if(e.type==='finish')this.showResults(e.result);}
 toast(title,detail){this.$('toast').textContent=title;let small=document.createElement('small');small.textContent=detail||'';this.$('toast').appendChild(small);this.$('toast').classList.add('show');this.toastUntil=this.time+2.0;}
 timeString(t,decimal=false){t=Math.max(0,Number(t)||0);let min=Math.floor(t/60),sec=Math.floor(t%60),cs=Math.floor((t%1)*100);return String(min).padStart(2,'0')+':'+String(sec).padStart(2,'0')+(decimal?'.'+String(cs).padStart(2,'0'):'');}
 showResults(result){this.clearInput();document.body.dataset.screen='results';this.$('hud').hidden=true;this.$('pauseOverlay').hidden=true;this.$('resultsOverlay').hidden=false;let g=this.game,r=result,free=r.mode==='free';this.$('resultKicker').textContent=free?'THE SCENIC ROUTE / '+(r.distance/1000).toFixed(1)+' KM':r.completed?'THE MH 04 CIRCUIT / COMPLETE':'THE CLOCK WON THIS ROUND';this.$('resultTitle').innerHTML=free?'Good roads.<br><em>Great detour.</em>':r.completed?'Thane,<br><em>tamed.</em>':'One more<br><em>run?</em>';this.$('medalValue').textContent=r.medal;this.$('medalValue').style.fontSize=r.medal.length>8?'10px':'';this.$('resultPosition').textContent=free?'SUNDAY STATE OF MIND':r.completed?['','1ST','2ND','3RD','4TH'][r.position]+' PLACE':Math.round(r.distance/this.route.length*100)+'% COMPLETE';this.$('finalScore').textContent=r.score.toLocaleString('en-IN');this.$('resultTime').textContent=this.timeString(r.time,true);this.$('resultTopSpeed').textContent=r.topSpeed+' km/h';this.$('resultNearMisses').textContent=r.nearMisses;this.$('resultChai').textContent=r.pickups;this.$('resultHits').textContent=r.collisions;this.$('resultDrift').textContent=r.drift+'s';this.$('resultMessage').textContent=free?'No rush. No deadline. Just '+(r.distance/1000).toFixed(1)+' km well spent.':!r.completed?'Boost on the straights. Chai refills your charge. Each checkpoint adds more time.':r.position===1?'The hills have a new local legend. The rickshaws are requesting a rematch.':r.collisions>9?'Less contact, more glory. Try the horn before threading the next gap.':'A proper Thane run. There is a faster line hiding in those Yeoor bends.';
 let old=this.saved.scores.filter(s=>s.mode===r.mode&&s.completed),best=Math.max(0,...old.map(s=>s.score)),saveEligible=free?r.distance>50:r.completed;if(saveEligible){this.saved.scores.push(r);this.saved.scores.sort((a,b)=>b.score-a.score);this.saved.scores=this.saved.scores.slice(0,30);let ok=TR.Store.save(this.saved);this.$('recordStatus').textContent=ok?(r.score>best?'NEW LOCAL BEST ↗':'SAVED ON THIS DEVICE'):'STORAGE UNAVAILABLE · SCORE NOT SAVED';}else this.$('recordStatus').textContent='FINISH THE CIRCUIT TO SAVE A RECORD';this.renderRecords(this.$('miniRecords'),r.mode,3);this.audio.update(g);this.$('raceAgainButton').focus();}
 renderRecords(el,mode=null,limit=10){el.replaceChildren();let rows=this.saved.scores.filter(s=>!mode||s.mode===mode).slice(0,limit);let head=document.createElement('div');head.className='mini-records-head';head.textContent=mode?'YOUR BEST RUNS / '+{rush:'SUNSET SPRINT',monsoon:'MONSOON MADNESS',free:'SUNDAY DRIVE'}[mode]:'LOCAL RECORDS / THIS BROWSER';el.appendChild(head);if(!rows.length){let p=document.createElement('p');p.className='empty-records';p.textContent='Your first great run belongs here.';el.appendChild(p);return;}let table=document.createElement('table');table.className='records-table';for(let [i,r]of rows.entries()){let tr=document.createElement('tr');for(let [j,value]of [String(i+1).padStart(2,'0'),TR.CARS[r.car]?.name||'Racer',this.timeString(r.time,true),Math.round(r.score).toLocaleString('en-IN')].entries()){let td=document.createElement('td');td.textContent=value;if(j===1){let small=document.createElement('small');small.textContent=({rush:'SUNSET SPRINT',monsoon:'MONSOON',free:'SUNDAY DRIVE'}[r.mode]||'RUN')+' · '+r.medal;td.appendChild(small);}tr.appendChild(td);}table.appendChild(tr);}el.appendChild(table);}
 openRecords(){this.$('infoEyebrow').textContent='BRAGGING RIGHTS / NO SIGN-IN';this.$('infoTitle').textContent='Your local legends.';this.renderRecords(this.$('infoContent'),null,10);this.$('infoOverlay').hidden=false;this.$('closeInfo').focus();}
 openAbout(){this.$('infoEyebrow').textContent='BUILT FOR THE DETOUR';this.$('infoTitle').textContent='A love letter to Thane.';this.$('infoContent').innerHTML=`<p>An original, hand-built 3D arcade game inspired by Upvan Lake, the Yeoor hills, Pokhran Road No. 2, Neelkanth Heights and Vasant Vihar. The scenery and connecting roads are artistic approximations. This is a fictional closed-course race, not a real-world map, access guide or driving simulator.</p><div class="info-meta"><span>3 RIDES</span><span>3 MODES</span><span>5.1 KM CIRCUIT</span><span>100% OFFLINE</span></div><h3>How to own the hills</h3><p>Auto throttle is on by default. Steer with A / D or the arrow keys. Hold Space for boost, Shift while steering for a drift, and S to brake. H sounds your horn and encourages traffic ahead to pull aside. T switches auto throttle. C changes camera. M toggles sound; N toggles the original synth soundtrack. P pauses. R restarts.</p><p>Chai cups restore 35% boost and award 250 base points. Close, clean overtakes award 100 base points and build your multiplier. Drifting regenerates boost. Clean checkpoints award 500 points; other checkpoints award 200. Contacts cost 180 points, potholes 80. Finish for a 5,000-point bonus plus time and position bonuses. Rickshaw pickup/overtake rewards get a 25% bonus. Sunday Drive has no time limit.</p><h3>Keep it playful</h3><p>All racing stays in the game. There are no real traffic rules, road conditions, wildlife movements or entry restrictions represented here. People and boats are scenery, not targets.</p><h3>Credits & privacy</h3><p>Original geometry, artwork, code, sound effects and synthesized music. No downloaded art assets, ads, analytics, accounts or external runtime dependencies. Records and settings stay in local browser storage; there is no global leaderboard.</p><p>Concept reference: <a href="https://orr-rush-bengaluru.ravitheja.chatgpt.site/" target="_blank" rel="noopener noreferrer">ORR Rush · Bengaluru</a>. Geographic inspiration: <a href="https://maharashtratourism.gov.in/districts/thane/" target="_blank" rel="noopener noreferrer">Maharashtra Tourism · Thane</a>. No reference-game code or assets are included.</p>`;this.$('infoOverlay').hidden=false;this.$('closeInfo').focus();}
 async copyRun(){let r=this.game.result;if(!r)return;let txt='THANE RUSH · '+r.medal+'\n'+Math.round(r.score).toLocaleString('en-IN')+' points · '+this.timeString(r.time,true)+' · '+TR.CARS[r.car].name+'\n'+r.nearMisses+' clean overtakes. '+r.pickups+' chai pickups.\nUpvan → Yeoor → Neelkanth. Beat that detour.';let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(txt);ok=true;}else{let ta=document.createElement('textarea');ta.value=txt;ta.style.cssText='position:fixed;opacity:0';document.body.appendChild(ta);ta.select();ok=document.execCommand('copy');ta.remove();}}catch(e){}this.$('copyButton').textContent=ok?'COPIED ✓':'COPY UNAVAILABLE';setTimeout(()=>this.$('copyButton').textContent='COPY RUN',2200);}
 resize(){if(!this.R)return;this.R.resize();let fx=this.$('fx');fx.width=innerWidth;fx.height=innerHeight;}
 updateHUD(){let g=this.game,z=this.route.zones[g.zone],d=Math.max(0,this.route.length-(g.s%this.route.length));this.$('positionValue').textContent=g.mode==='free'?'∞':g.position();this.$('positionValue').nextElementSibling.textContent=g.mode==='free'?'': '/ 4';this.$('sectorIndex').textContent=String(g.zone+1).padStart(2,'0')+' / 06 · '+(g.mode==='monsoon'?'WET ROADS':g.mode==='free'?'SUNDAY DRIVE':'SUNSET SPRINT');this.$('sectorName').textContent=z.name;this.$('distanceValue').textContent=g.mode==='free'?(g.s/1000).toFixed(2)+' km explored':(d/1000).toFixed(2)+' km to finish';this.$('progressBar').style.width=((g.s%this.route.length)/this.route.length*100)+'%';this.$('timerLabel').textContent=g.mode==='free'?'NO RUSH':'CHECKPOINT TIMER';this.$('timeValue').textContent=g.mode==='free'?this.timeString(g.time):this.timeString(Math.ceil(g.remaining));this.$('elapsedValue').textContent=g.mode==='free'?'JUST ENJOY THE DRIVE':'RUN '+this.timeString(g.time,true);this.$('timeValue').parentElement.classList.toggle('urgent',g.mode!=='free'&&g.remaining<12);this.$('scoreValue').textContent=String(Math.floor(g.score)).padStart(5,'0');this.$('comboValue').textContent=g.drifting?'DRIFTING · RECHARGING BOOST':g.combo>1?'CLEAN OVERTAKES · ×'+g.combo:'DRIVE CLEAN. SCORE BIG.';this.$('speedValue').textContent=Math.floor(g.speed*3.6);this.$('gearValue').textContent=g.speed<1?'N':Math.min(6,1+Math.floor(g.speed*3.6/42));this.$('revBar').style.width=Math.min(100,g.speed/g.spec.boost*100)+'%';this.$('boostValue').textContent=Math.floor(g.nitro)+'%';this.$('boostBar').style.width=g.nitro+'%';this.$('speedNote').textContent=g.boosting?'A LITTLE EXTRA CHAOS ↗':g.offroad?'BACK ON THE ROAD ↗':g.drifting?'DRIFT TO RECHARGE':g.nitroLock?'RECHARGING…':'HOLD SPACE TO BOOST';this.$('speedValue').closest('.speed-panel').classList.toggle('boosting',g.boosting);this.$('lapValue').textContent=g.mode==='free'?'LAP '+(g.lap+1):(this.route.length/1000).toFixed(1)+' KM';let bend=this.route.curvature(g.s+42);this.$('nextTurn').firstChild.textContent=Math.abs(bend)<.0014?'↑ ':bend<0?'↰ ':'↱ ';this.$('nextTurn').querySelector('span').textContent=Math.abs(bend)<.0014?'OPEN IT UP':Math.abs(bend)>.005?'TIGHT BEND AHEAD':'BEND AHEAD';this.$('hornButton').disabled=g.hornCooldown>0;this.$('touchHorn').disabled=g.hornCooldown>0;this.$('tutorial').hidden=this.tutorialDismissed||g.time>9;}
 drawMap(canvas,menu=false){let c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pad=menu?18:20,cw=w-pad*2,ch=h-pad*2;let minX=-1220,maxX=175,minZ=-530,maxZ=635,s=Math.min(cw/(maxX-minX),ch/(maxZ-minZ)),ox=(w-(maxX-minX)*s)/2,oz=(h-(maxZ-minZ)*s)/2,project=p=>[ox+(p[0]-minX)*s,oz+(p[2]-minZ)*s];c.clearRect(0,0,w,h);let lp=project([-180,0,-45]);c.beginPath();c.ellipse(lp[0],lp[1],177*s,195*s,0,0,6.283);c.fillStyle='#70aaa648';c.fill();c.strokeStyle='#91c5b458';c.lineWidth=1;c.stroke();let pts=[];for(let i=0;i<=240;i++)pts.push(project(this.route.point(i/240*this.route.length)));c.lineCap='round';c.lineJoin='round';c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle='#7894735c';c.lineWidth=menu?7:7;c.stroke();if(!menu){let count=Math.floor(((this.game.s%this.route.length)/this.route.length)*240);c.beginPath();pts.slice(0,count+1).forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle='#d8f76b';c.lineWidth=3.5;c.stroke();}else{c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle='#c6d7a9';c.lineWidth=2.5;c.stroke();}
 for(let z of this.route.zones){let p=project(this.route.point(z.at*this.route.length));c.beginPath();c.arc(...p,menu?4:3,0,6.283);c.fillStyle=z.color;c.fill();}if(menu){c.font='11px monospace';c.fillStyle='#a4c2a0';c.fillText('YEOOR',22,55);c.fillStyle='#91c5b4';c.fillText('UPVAN',lp[0]-19,lp[1]+5);c.fillStyle='#d3c39b';c.fillText('START',pts[0][0]+9,pts[0][1]+2);return;}
 if(this.game.mode!=='free')for(let[i,v]of this.game.rivals.entries()){let p=project(this.route.point(v.s));c.beginPath();c.arc(...p,4,0,6.283);c.fillStyle=['#f09673','#9ec9eb','#c1a3d9'][i];c.fill();}let p=project(this.route.point(this.game.s)),t=this.route.frame(this.game.s).t;c.save();c.translate(...p);c.rotate(Math.atan2(t[2],t[0])+Math.PI/2);c.shadowColor='#d8f76b';c.shadowBlur=10;c.beginPath();c.moveTo(0,-8);c.lineTo(5,6);c.lineTo(0,3);c.lineTo(-5,6);c.closePath();c.fillStyle='#e3fa93';c.fill();c.restore();}
 render(dt){let g=this.game,menu=g.state==='menu',R=this.R,W=this.world,route=this.route,V=TR.V,weather=this.weather();let ps=menu?900:g.mode==='free'?g.s%route.length:Math.min(g.s,route.length-.01),px=menu?-1.65:g.x,f=route.frame(ps),carP=route.at(ps,px,.035),eye,target;
 if(menu){let orbit=this.reduced?0:Math.sin(this.time*.06)*1.4;eye=V.add(V.add(carP,V.scale(f.r,8.5+orbit)),V.add(V.scale(f.t,-14),[0,7.3,0]));target=V.add(V.add(carP,V.scale(f.t,5)),V.add(V.scale(f.r,-10.0),[0,1.9,0]));}
 else if(this.cameraMode){eye=route.at(ps+1,g.x,1.55);target=route.at(ps+35,g.x*.75,1.7);}
 else{let zoom=g.boosting&&!this.reduced?1.5:0;eye=route.at(ps-10.8-zoom,g.x*.94,5.0+zoom*.18);target=route.at(ps+17,g.x*.35,1.35);}
 if(!this.cameraEye){this.cameraEye=eye;this.cameraTarget=target;}let blend=1-Math.exp(-dt*(menu?3.2:this.cameraMode?18:10));this.cameraEye=V.lerp(this.cameraEye,eye,blend);this.cameraTarget=V.lerp(this.cameraTarget,target,blend);let shake=this.reduced?0:g.shake*(g.state==='running'?.2:0),camera=V.add(this.cameraEye,[Math.sin(this.time*73)*shake,Math.cos(this.time*81)*shake,0]);R.begin(camera,this.cameraTarget,weather,this.time,menu?49:(this.cameraMode?67:58)+(g.boosting&&!this.reduced?7:0));W.drawScene(camera,this.time);
 // Only nearby dynamic geometry is submitted, keeping low-powered devices responsive.
 let drawVehicle=(v,s,x,player=false)=>{let vf=route.frame(s),p=route.at(s,x,.055),dist=V.len(V.sub(p,camera));if(dist>310)return;let y=vf.yaw,roll=0;if(player){y-=Math.atan2(g.vx,Math.max(g.speed,8))*(g.drifting?.9:.38);roll=TR.clamp(-g.vx*.007,-.075,.075);p[1]+=(g.offroad&&!this.reduced?Math.sin(this.time*30)*.055:0);}R.draw(W.carShadow,TR.M.model(route.at(s,x,.035),vf.yaw,[1,1,1],0,vf.pitch),{alpha:true});if(!player||menu||!this.cameraMode)R.draw(W.models[v.kind],TR.M.model(p,y,[1,1,1],roll,vf.pitch));if(player&&!menu&&g.boosting&&!this.cameraMode)R.draw(W.flame,TR.M.model(p,y,[1,1,.65+Math.sin(this.time*60)*.2],roll,vf.pitch),{unlit:true});};
 for(let v of g.traffic){let s=menu?v.s+this.time*v.speed:v.s;drawVehicle(v,s,v.x);}
 if(!menu&&g.mode!=='free')for(let v of g.rivals)drawVehicle(v,v.s,v.x);
 if(!menu)for(let item of g.items){let s=item.s+g.lap*route.length;if(item.used||s-g.s< -10||s-g.s>210)continue;let p=route.at(s,item.x,1.0+Math.sin(this.time*3+item.phase)*.16);R.draw(W.pickup,TR.M.model(p,this.time*1.5,[1.1,1.1,1.1]),{unlit:true});}
 if(!menu)for(let h of g.hazards){let s=h.s+g.lap*route.length;if(s-g.s< -30||s-g.s>230)continue;let f=route.frame(s);R.draw(h.type==='cone'?W.cone:W.pothole,TR.M.model(route.at(s,h.x,.035),f.yaw,[1,1,1],0,f.pitch));}
 drawVehicle({kind:this.car},ps,px,true);if(!menu&&g.hornPulse>0){let expand=1+(1-g.hornPulse/.65)*8;R.draw(W.horn,TR.M.model(route.at(ps,g.x,.04),f.yaw,[expand,1,expand],0,f.pitch),{alpha:true,unlit:true});}R.labels();this.renderFX(weather,g,menu);}
 renderFX(weather,g,menu){let c=this.fx,w=c.canvas.width,h=c.canvas.height;c.clearRect(0,0,w,h);if(weather==='rain'){c.strokeStyle='rgba(225,243,236,.29)';c.lineWidth=1;let n=this.reduced?55:175;c.beginPath();for(let i=0;i<n;i++){let x=((i*137.7+Math.sin(i)*87-this.time*65)%(w+150)+(w+150))%(w+150)-80,y=((i*79.13+this.time*(380+(i%5)*80))%(h+100))-60;c.moveTo(x,y);c.lineTo(x-4,y+14+(i%4)*4);}c.stroke();if(!menu&&this.cameraMode&&!this.reduced){let phase=this.time%3.7;if(phase<1.7){let angle=-1.35+Math.sin(phase/1.7*Math.PI)*1.6;c.strokeStyle='rgba(10,29,28,.88)';c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(w*.51,h*1.05);c.lineTo(w*.51+Math.cos(angle)*w*.37,h*1.05+Math.sin(angle)*h*.65);c.stroke();}}}if(g.boosting&&g.state==='running'&&!this.reduced){c.lineWidth=1.5;c.strokeStyle='rgba(232,251,193,.30)';for(let i=0;i<28;i++){let a=i/28*6.283,phase=((this.time*1.7+i*.34)%1),r=.47+phase*.4;c.beginPath();c.moveTo(w*.5+Math.cos(a)*w*r,h*.44+Math.sin(a)*h*r);c.lineTo(w*.5+Math.cos(a)*w*(r+.08),h*.44+Math.sin(a)*h*(r+.08));c.stroke();}}this.$('impact').style.opacity=g.state==='running'&&!this.reduced?g.shake*.52:0;}
 frame(now){if(!this.initialized)return;let dt=Math.min(.1,(now-this.lastTime)/1000);this.lastTime=now;this.time+=dt;this.accumulator+=dt;let input=this.input(),steps=0;while(this.accumulator>=1/120&&steps<12){this.game.step(1/120,input);this.accumulator-=1/120;steps++;}this.audio.update(this.game);this.render(dt);if(now-this.lastUI>65){if(this.game.state==='running'||this.game.state==='countdown')this.updateHUD();this.lastUI=now;}if(now-this.lastMap>125&&this.game.state!=='menu'){this.drawMap(this.$('minimap'));this.lastMap=now;}if(this.game.state==='running'&&this.goUntil&&this.time>this.goUntil)this.$('countdown').textContent='';if(this.time>this.toastUntil)this.$('toast').classList.remove('show');if(this.time>this.bannerUntil)this.$('checkpointBanner').classList.remove('show');requestAnimationFrame(this.frame);}
 showError(message){this.$('loading').hidden=true;this.$('errorOverlay').hidden=false;this.$('errorText').textContent=message;}
};
window.addEventListener('load',()=>{setTimeout(()=>{try{window.thaneRush=new TR.App();}catch(e){document.getElementById('loading').hidden=true;document.getElementById('errorOverlay').hidden=false;document.getElementById('errorText').textContent=e.message;console.error(e);}},40);});
