/* Thane Rush — small, dependency-free WebGL renderer. Original game code. */
'use strict';
const TR = {};
TR.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
TR.mix=(a,b,t)=>a+(b-a)*t;
TR.smooth=(a,b,t)=>{t=TR.clamp((t-a)/(b-a),0,1);return t*t*(3-2*t);};
TR.V={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],scale:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len:a=>Math.hypot(...a),norm:a=>{let l=Math.hypot(...a)||1;return a.map(x=>x/l);},lerp:(a,b,t)=>a.map((x,i)=>TR.mix(x,b[i],t))};
TR.M={
 identity:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),
 perspective:(f,a,n,z)=>{let s=1/Math.tan(f/2);return new Float32Array([s/a,0,0,0,0,s,0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0]);},
 look:(eye,target)=>{let V=TR.V,z=V.norm(V.sub(eye,target)),x=V.norm(V.cross([0,1,0],z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1]);},
 mul:(a,b)=>{let r=new Float32Array(16);for(let c=0;c<4;c++)for(let i=0;i<4;i++){let v=0;for(let j=0;j<4;j++)v+=a[j*4+i]*b[c*4+j];r[c*4+i]=v;}return r;},
 model:(p,yaw=0,scale=[1,1,1],roll=0,pitch=0)=>{let c=Math.cos(yaw),s=Math.sin(yaw),cr=Math.cos(roll),sr=Math.sin(roll),cp=Math.cos(pitch),sp=Math.sin(pitch);let a=new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,p[0],p[1],p[2],1]);let b=new Float32Array([cr,sr,0,0,-sr*cp,cr*cp,sp,0,sr*sp,-cr*sp,cp,0,0,0,0,1]);let m=TR.M.mul(a,b);for(let i=0;i<3;i++)for(let j=0;j<3;j++)m[i*4+j]*=scale[i];return m;},
 project:(p,m)=>{let x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15];return [(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,w];}
};
TR.rgb=(h,a=1)=>{if(Array.isArray(h))return h;h=h.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255,a];};
TR.rng=(seed=74)=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
TR.MeshBuilder=class{
 constructor(){this.data=[];}
 tri(a,b,c,col,normal){let n=normal||TR.V.norm(TR.V.cross(TR.V.sub(b,a),TR.V.sub(c,a))),co=TR.rgb(col);for(let p of[a,b,c])this.data.push(...p,...n,co[0],co[1],co[2],co[3]===undefined?1:co[3]);return this;}
 quad(a,b,c,d,col,n){this.tri(a,b,c,col,n);this.tri(a,c,d,col,n);return this;}
 box(p,size,col,yaw=0){let[hx,hy,hz]=size.map(x=>x/2),co=TR.rgb(col),c=Math.cos(yaw),s=Math.sin(yaw);let v=[[-hx,-hy,-hz],[hx,-hy,-hz],[hx,hy,-hz],[-hx,hy,-hz],[-hx,-hy,hz],[hx,-hy,hz],[hx,hy,hz],[-hx,hy,hz]].map(q=>[p[0]+q[0]*c+q[2]*s,p[1]+q[1],p[2]-q[0]*s+q[2]*c]);for(let f of[[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])this.quad(v[f[0]],v[f[1]],v[f[2]],v[f[3]],co);return this;}
 cyl(p,rt,rb,h,col,segments=8){for(let i=0;i<segments;i++){let a=i/segments*Math.PI*2,b=(i+1)/segments*Math.PI*2,A=[p[0]+Math.cos(a)*rb,p[1],p[2]+Math.sin(a)*rb],B=[p[0]+Math.cos(b)*rb,p[1],p[2]+Math.sin(b)*rb],C=[p[0]+Math.cos(b)*rt,p[1]+h,p[2]+Math.sin(b)*rt],D=[p[0]+Math.cos(a)*rt,p[1]+h,p[2]+Math.sin(a)*rt];this.quad(A,D,C,B,col);this.tri([p[0],p[1]+h,p[2]],C,D,col,[0,1,0]);}return this;}
 ellipsoid(p,r,col,seg=9,rings=5){let pt=(i,j)=>{let a=i/seg*Math.PI*2,b=j/rings*Math.PI;return[p[0]+Math.cos(a)*Math.sin(b)*r[0],p[1]+Math.cos(b)*r[1],p[2]+Math.sin(a)*Math.sin(b)*r[2]];};for(let j=0;j<rings;j++)for(let i=0;i<seg;i++)this.quad(pt(i,j),pt(i+1,j),pt(i+1,j+1),pt(i,j+1),col);return this;}
 ring(p,r,w,col,seg=32){for(let i=0;i<seg;i++){let a=i/seg*6.283,b=(i+1)/seg*6.283;this.quad([p[0]+Math.cos(a)*r,p[1],p[2]+Math.sin(a)*r],[p[0]+Math.cos(b)*r,p[1],p[2]+Math.sin(b)*r],[p[0]+Math.cos(b)*(r+w),p[1],p[2]+Math.sin(b)*(r+w)],[p[0]+Math.cos(a)*(r+w),p[1],p[2]+Math.sin(a)*(r+w)],col,[0,1,0]);}return this;}
 merge(other){for(let x of other.data)this.data.push(x);return this;}
};
TR.Renderer=class{
 constructor(canvas){this.canvas=canvas;const opts={antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true};this.gl=canvas.getContext('webgl',opts)||canvas.getContext('experimental-webgl',opts);if(!this.gl)throw Error('WebGL is not available. Enable graphics acceleration or try another browser.');let g=this.gl;
 const vert=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec4 aColor;uniform mat4 uVP,uModel;varying vec3 vNormal,vWorld;varying vec4 vColor;void main(){vec4 p=uModel*vec4(aPosition,1.);vWorld=p.xyz;vNormal=normalize(mat3(uModel)*aNormal);vColor=aColor;gl_Position=uVP*p;}`;
 const frag=`precision mediump float;varying vec3 vNormal,vWorld;varying vec4 vColor;uniform vec3 uEye,uFog,uSun;uniform float uFogNear,uFogFar,uTime,uWet,uNight,uWater,uUnlit;void main(){vec3 n=normalize(vNormal);float sun=max(dot(n,normalize(uSun)),0.);float sky=.5+.5*n.y;vec3 light=mix(vec3(.50,.55,.53),vec3(.91,.95,.88),sky)+sun*vec3(.27,.19,.08)*(1.-uWet*.5);light=mix(light,vec3(.28,.39,.53)+sun*.13,uNight);vec3 col=vColor.rgb*mix(light,vec3(1.),uUnlit);if(uWater>.5){float w=sin(vWorld.x*.09+uTime*.65)+sin(vWorld.z*.13-uTime*.8);vec3 view=normalize(uEye-vWorld);float fres=pow(1.-max(view.y,0.),2.);col=mix(vec3(.13,.37,.37),uFog*.85,fres*.75);float ripple=sin(vWorld.x*.55+sin(vWorld.z*.12+uTime)*2.+uTime*1.2);float spark=pow(max(0.,ripple),25.);float band=pow(max(0.,dot(normalize(vec3(view.x,0.,view.z)),normalize(vec3(uSun.x,0.,uSun.z)))),18.);col+=vec3(.72,.45,.14)*spark*band*(.3+.7*fres)*(1.-uWet);col+=w*.013;col=mix(col,col*vec3(.30,.45,.70),uNight); }float dist=length(uEye-vWorld);float fog=smoothstep(uFogNear,uFogFar,dist);col=mix(col,uFog,fog);gl_FragColor=vec4(col,vColor.a);}`;
 this.program=this.compile(vert,frag);this.loc={};for(let n of['aPosition','aNormal','aColor'])this.loc[n]=g.getAttribLocation(this.program,n);for(let n of['uVP','uModel','uEye','uFog','uSun','uFogNear','uFogFar','uTime','uWet','uNight','uWater','uUnlit'])this.loc[n]=g.getUniformLocation(this.program,n);
 this.skyProgram=this.compile(`attribute vec2 aPosition;varying vec2 vUV;void main(){vUV=aPosition*.5+.5;gl_Position=vec4(aPosition,.9999,1.);}`,`precision mediump float;varying vec2 vUV;uniform vec2 uSunScreen,uResolution;uniform float uWet,uNight,uTime;void main(){float y=vUV.y;vec3 dusk=mix(vec3(.96,.68,.44),vec3(.27,.53,.62),smoothstep(.15,1.,y));vec3 rain=mix(vec3(.60,.70,.70),vec3(.18,.30,.37),y);vec3 night=mix(vec3(.27,.28,.43),vec3(.028,.064,.13),y);vec3 c=mix(mix(dusk,rain,uWet),night,uNight);vec2 p=(vUV-uSunScreen)*vec2(uResolution.x/uResolution.y,1.);float d=length(p);float sun=1.-smoothstep(.030,.032,d);float glow=exp(-d*9.)*.26; c+=vec3(1.,.58,.19)*glow*(1.-uWet)*(1.-uNight);c=mix(c,vec3(1.,.88,.57),sun*(1.-uWet)*(1.-uNight));float cloud=sin(vUV.x*12.+uTime*.005+sin(y*16.)*.7)*sin(y*38.+sin(vUV.x*8.));c=mix(c,mix(vec3(.99,.81,.65),vec3(.60,.67,.68),uWet),smoothstep(.55,.85,cloud)*.18*(1.-uNight));if(uNight>.5){vec2 q=floor(vUV*vec2(330.,180.));float r=fract(sin(dot(q,vec2(12.9898,78.233)))*43758.5453);c+=step(.996,r)*smoothstep(.3,.7,y)*.55;}gl_FragColor=vec4(c,1.);}`);
 this.skyLoc={};for(let n of['uSunScreen','uResolution','uWet','uNight','uTime'])this.skyLoc[n]=g.getUniformLocation(this.skyProgram,n);this.skyAttr=g.getAttribLocation(this.skyProgram,'aPosition');this.skyBuffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.skyBuffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),g.STATIC_DRAW);
 this.texProgram=this.compile(`attribute vec3 aPosition;attribute vec2 aUV;uniform mat4 uVP;varying vec2 vUV;varying vec3 vWorld;void main(){vUV=aUV;vWorld=aPosition;gl_Position=uVP*vec4(aPosition,1.);}`,`precision mediump float;uniform sampler2D uTexture;uniform vec3 uEye,uFog;uniform float uFogFar,uNight;varying vec2 vUV;varying vec3 vWorld;void main(){vec4 c=texture2D(uTexture,vUV);if(c.a<.1)discard;c.rgb=mix(c.rgb,uFog,smoothstep(uFogFar*.35,uFogFar,length(vWorld-uEye)));gl_FragColor=c;}`);
 this.texLoc={};for(let n of['aPosition','aUV'])this.texLoc[n]=g.getAttribLocation(this.texProgram,n);for(let n of['uVP','uTexture','uEye','uFog','uFogFar','uNight'])this.texLoc[n]=g.getUniformLocation(this.texProgram,n);this.textMeshes=[];this.identity=TR.M.identity();this.quality=1;this.resize();g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);this.drawCalls=0;
 }
 compile(v,f){let g=this.gl,compile=(s,t)=>{let sh=g.createShader(t);g.shaderSource(sh,s);g.compileShader(sh);if(!g.getShaderParameter(sh,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(sh));return sh;};let p=g.createProgram(),vs=compile(v,g.VERTEX_SHADER),fs=compile(f,g.FRAGMENT_SHADER);g.attachShader(p,vs);g.attachShader(p,fs);g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));g.deleteShader(vs);g.deleteShader(fs);return p;}
 resize(){let d=Math.min(window.devicePixelRatio||1,this.quality===0?1:1.6),w=Math.round(innerWidth*d*(this.quality===0?.8:1)),h=Math.round(innerHeight*d*(this.quality===0?.8:1));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.gl.viewport(0,0,w,h);}
 upload(builder){let g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(builder.data),g.STATIC_DRAW);return{buffer:b,count:builder.data.length/10};}
 label(p,yaw,w,h,line1,line2='',style='green'){
 let cv=document.createElement('canvas');cv.width=512;cv.height=128;let c=cv.getContext('2d'),bg=style==='lime'?'#d7f75c':style==='warm'?'#f5dca7':style==='dark'?'#142a2a':'#176658',fg=style==='lime'||style==='warm'?'#162827':'#f5f0da';c.fillStyle=bg;c.fillRect(0,0,512,128);c.strokeStyle=fg;c.lineWidth=3;c.strokeRect(7,7,498,114);c.textAlign='center';c.fillStyle=fg;c.font='bold 36px Arial';c.fillText(line1,256,line2?55:77);if(line2){c.font='18px Arial';c.fillText(line2,256,92);}let g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,cv);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);
 let right=[Math.cos(yaw)*w/2,0,-Math.sin(yaw)*w/2],V=TR.V,a=V.add(p,[-right[0],-h/2,-right[2]]),b=V.add(p,[right[0],-h/2,right[2]]),cc=V.add(p,[right[0],h/2,right[2]]),d=V.add(p,[-right[0],h/2,-right[2]]),data=[...a,0,0,...b,1,0,...cc,1,1,...a,0,0,...cc,1,1,...d,0,1],buffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);this.textMeshes.push({p,texture:t,buffer});
 }
 begin(eye,target,weather,time,fov=57){let g=this.gl;this.eye=eye;this.weather=weather;this.fog=weather==='rain'?[.51,.62,.63]:weather==='night'?[.13,.18,.27]:[.76,.69,.53];this.fogFar=weather==='rain'?680:1150;this.sun=[-1.3,.75,-.75];this.vp=TR.M.mul(TR.M.perspective(fov*Math.PI/180,this.canvas.width/this.canvas.height,.15,4200),TR.M.look(eye,target));this.drawCalls=0;g.clearColor(...this.fog,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.disable(g.DEPTH_TEST);g.useProgram(this.skyProgram);g.bindBuffer(g.ARRAY_BUFFER,this.skyBuffer);g.enableVertexAttribArray(this.skyAttr);g.vertexAttribPointer(this.skyAttr,2,g.FLOAT,false,0,0);let sunPos=TR.M.project(TR.V.add(eye,TR.V.scale(TR.V.norm(this.sun),2500)),this.vp);g.uniform2f(this.skyLoc.uSunScreen,sunPos[0]*.5+.5,sunPos[1]*.5+.5);g.uniform2f(this.skyLoc.uResolution,this.canvas.width,this.canvas.height);g.uniform1f(this.skyLoc.uWet,weather==='rain'?1:0);g.uniform1f(this.skyLoc.uNight,weather==='night'?1:0);g.uniform1f(this.skyLoc.uTime,time);g.drawArrays(g.TRIANGLES,0,6);g.disableVertexAttribArray(this.skyAttr);g.enable(g.DEPTH_TEST);g.useProgram(this.program);g.uniformMatrix4fv(this.loc.uVP,false,this.vp);g.uniform3fv(this.loc.uEye,eye);g.uniform3fv(this.loc.uFog,this.fog);g.uniform3fv(this.loc.uSun,this.sun);g.uniform1f(this.loc.uFogNear,this.fogFar*.28);g.uniform1f(this.loc.uFogFar,this.fogFar);g.uniform1f(this.loc.uWet,weather==='rain'?1:0);g.uniform1f(this.loc.uNight,weather==='night'?1:0);g.uniform1f(this.loc.uTime,time);g.uniform1f(this.loc.uWater,0);g.uniform1f(this.loc.uUnlit,0);
 }
 draw(mesh,model=null,opt={}){if(!mesh||!mesh.count)return;let g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,mesh.buffer);for(let [n,size,off]of[['aPosition',3,0],['aNormal',3,12],['aColor',4,24]]){g.enableVertexAttribArray(this.loc[n]);g.vertexAttribPointer(this.loc[n],size,g.FLOAT,false,40,off);}g.uniformMatrix4fv(this.loc.uModel,false,model||this.identity);g.uniform1f(this.loc.uWater,opt.water?1:0);g.uniform1f(this.loc.uUnlit,opt.unlit?1:0);if(opt.alpha){g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);}g.drawArrays(g.TRIANGLES,0,mesh.count);if(opt.alpha){g.disable(g.BLEND);g.depthMask(true);}this.drawCalls++;}
 labels(){let g=this.gl;for(let n of['aPosition','aNormal','aColor'])g.disableVertexAttribArray(this.loc[n]);g.useProgram(this.texProgram);g.uniformMatrix4fv(this.texLoc.uVP,false,this.vp);g.uniform3fv(this.texLoc.uEye,this.eye);g.uniform3fv(this.texLoc.uFog,this.fog);g.uniform1f(this.texLoc.uFogFar,this.fogFar);g.uniform1f(this.texLoc.uNight,this.weather==='night'?1:0);g.uniform1i(this.texLoc.uTexture,0);g.activeTexture(g.TEXTURE0);for(let m of this.textMeshes){if(TR.V.len(TR.V.sub(m.p,this.eye))>560)continue;g.bindBuffer(g.ARRAY_BUFFER,m.buffer);g.enableVertexAttribArray(this.texLoc.aPosition);g.vertexAttribPointer(this.texLoc.aPosition,3,g.FLOAT,false,20,0);g.enableVertexAttribArray(this.texLoc.aUV);g.vertexAttribPointer(this.texLoc.aUV,2,g.FLOAT,false,20,12);g.bindTexture(g.TEXTURE_2D,m.texture);g.drawArrays(g.TRIANGLES,0,6);this.drawCalls++;}g.disableVertexAttribArray(this.texLoc.aPosition);g.disableVertexAttribArray(this.texLoc.aUV);}
};
