/* Compatibility renderer: the same 3D geometry, projected in Canvas 2D.
   Used only when WebGL is unavailable. No network, plugins or GPU required. */
TR.CanvasRenderer=class{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false,willReadFrequently:true});if(!this.ctx)throw Error('The browser could not create a drawing surface.');this.quality=0;this.identity=TR.M.identity();this.textMeshes=[];this.drawCalls=0;this.resize();}
 resize(){let d=this.quality?1:.82;this.canvas.width=Math.round(innerWidth*d);this.canvas.height=Math.round(innerHeight*d);}
 upload(b){return{data:new Float32Array(b.data),count:b.data.length/10};}
 label(p,yaw,w,h,line1,line2='',style='green'){let cv=document.createElement('canvas');cv.width=512;cv.height=128;let c=cv.getContext('2d'),bg=style==='lime'?'#d7f75c':style==='warm'?'#f5dca7':style==='dark'?'#142a2a':'#176658',fg=style==='lime'||style==='warm'?'#162827':'#f5f0da';c.fillStyle=bg;c.fillRect(0,0,512,128);c.strokeStyle=fg;c.lineWidth=3;c.strokeRect(7,7,498,114);c.fillStyle=fg;c.textAlign='center';c.font='bold 36px Arial';c.fillText(line1,256,line2?55:77);if(line2){c.font='18px Arial';c.fillText(line2,256,92);}let rr=[Math.cos(yaw)*w/2,0,-Math.sin(yaw)*w/2],corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>[p[0]+rr[0]*x,p[1]+h/2*y,p[2]+rr[2]*x]);this.textMeshes.push({p,cv,corners,pixels:c.getImageData(0,0,512,128).data});}
 begin(eye,target,weather,time,fov=57){this.eye=eye;this.weather=weather;this.fog=weather==='rain'?[.51,.62,.63]:weather==='night'?[.13,.18,.27]:[.76,.69,.53];this.fogFar=weather==='rain'?650:1250;this.time=time;this.view=TR.M.look(eye,target);this.vp=TR.M.mul(TR.M.perspective(fov*Math.PI/180,this.canvas.width/this.canvas.height,.15,4200),this.view);this.focal=this.canvas.height/(2*Math.tan(fov*Math.PI/360));this.queue=[];this.drawCalls=0;let c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.setTransform(1,0,0,1,0,0);c.globalAlpha=1;let grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,weather==='rain'?'#344f59':weather==='night'?'#081528':'#739daa');grad.addColorStop(.62,weather==='rain'?'#97acaa':weather==='night'?'#46516c':'#edbb88');grad.addColorStop(1,weather==='rain'?'#718a76':weather==='night'?'#253d3d':'#89986f');c.fillStyle=grad;c.fillRect(0,0,w,h);
 let sun=TR.M.project(TR.V.add(eye,TR.V.scale(TR.V.norm([-1.3,.75,-.75]),2400)),this.vp),sx=(sun[0]*.5+.5)*w,sy=(-sun[1]*.5+.5)*h;if(weather==='sunset'&&sun[2]>0){let glow=c.createRadialGradient(sx,sy,0,sx,sy,h*.22);glow.addColorStop(0,'#ffdda076');glow.addColorStop(1,'#ffcf7a00');c.fillStyle=glow;c.fillRect(0,0,w,h);c.fillStyle='#ffe5a4';c.beginPath();c.arc(sx,sy,h*.032,0,6.283);c.fill();}if(weather==='night'){c.fillStyle='#d2e8db';for(let i=0;i<75;i++){let x=(i*113.1)%w,y=(Math.sin(i*31)+1)*h*.19;c.globalAlpha=.3+(i%4)*.15;c.fillRect(x,y,1.2,1.2);}c.globalAlpha=1;}
 }
 camera(p){let m=this.view;return[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],-(m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14])];}
 screen(p){return[this.canvas.width/2+p[0]/p[2]*this.focal,this.canvas.height/2-p[1]/p[2]*this.focal];}
 draw(mesh,model=null,opt={}){if(!mesh)return;this.drawCalls++;let d=mesh.data,w=this.canvas.width,h=this.canvas.height,eye=this.eye,fg=this.fog,fogStart=this.fogFar*.28,night=this.weather==='night',V=TR.V;let trans=p=>!model?p:[model[0]*p[0]+model[4]*p[1]+model[8]*p[2]+model[12],model[1]*p[0]+model[5]*p[1]+model[9]*p[2]+model[13],model[2]*p[0]+model[6]*p[1]+model[10]*p[2]+model[14]];
 for(let i=0;i<d.length;i+=30){let a=trans([d[i],d[i+1],d[i+2]]),b=trans([d[i+10],d[i+11],d[i+12]]),cc=trans([d[i+20],d[i+21],d[i+22]]),cx=(a[0]+b[0]+cc[0])/3,cy=(a[1]+b[1]+cc[1])/3,cz=(a[2]+b[2]+cc[2])/3,n=[d[i+3],d[i+4],d[i+5]];if(model)n=V.norm([model[0]*n[0]+model[4]*n[1]+model[8]*n[2],model[1]*n[0]+model[5]*n[1]+model[9]*n[2],model[2]*n[0]+model[6]*n[1]+model[10]*n[2]]);if(n[0]*(eye[0]-cx)+n[1]*(eye[1]-cy)+n[2]*(eye[2]-cz)<-.01&&!opt.water)continue;
 let ca=this.camera(a),cb=this.camera(b),ccc=this.camera(cc);if(ca[2]<.2&&cb[2]<.2&&ccc[2]<.2)continue;let poly=[ca,cb,ccc];if(poly.some(p=>p[2]<.2)){let clipped=[];for(let j=0;j<poly.length;j++){let q=poly[j],r=poly[(j+1)%poly.length],qi=q[2]>=.2,ri=r[2]>=.2;if(qi)clipped.push(q);if(qi!==ri)clipped.push(V.lerp(q,r,(.2-q[2])/(r[2]-q[2])));}poly=clipped;}if(poly.length<3)continue;let pts=poly.map(p=>this.screen(p));if(pts.every(p=>p[0]<0)||pts.every(p=>p[0]>w)||pts.every(p=>p[1]<0)||pts.every(p=>p[1]>h))continue;
 let area=Math.abs((pts[1][0]-pts[0][0])*(pts[2][1]-pts[0][1])-(pts[2][0]-pts[0][0])*(pts[1][1]-pts[0][1]));if(area<(this.quality?.3:1.0))continue;let dist=Math.hypot(eye[0]-cx,eye[1]-cy,eye[2]-cz),fog=TR.smooth(fogStart,this.fogFar,dist),sky=.5+.5*n[1],sun=Math.max(0,n[0]*-.813+n[1]*.469+n[2]*-.469),col=[d[i+6],d[i+7],d[i+8]];if(opt.water)col=[.34,.53,.49];if(!opt.unlit&&!opt.water)col=col.map((v,j)=>v*(night?[.28,.39,.53][j]+sun*.13:TR.mix([.50,.55,.53][j],[.91,.95,.88][j],sky)+sun*[.27,.19,.08][j]));col=col.map((v,j)=>Math.round(TR.clamp(TR.mix(v,fg[j],fog),0,1)*255));let depth=poly.reduce((sum,p)=>sum+p[2],0)/poly.length;this.queue.push({pts,depth,z:poly.map(p=>1/p[2]),rgb:col,alpha:d[i+9]});
 }}
 labels(){
 let ctx=this.ctx,w=this.canvas.width,h=this.canvas.height,image=ctx.getImageData(0,0,w,h);this.pixels=image.data;this.p32=new Uint32Array(image.data.buffer);if(!this.depthBuffer||this.depthBuffer.length!==w*h)this.depthBuffer=new Float32Array(w*h);this.depthBuffer.fill(0);
 for(let pass=0;pass<2;pass++)for(let f of this.queue){if((f.alpha<.99)!==(pass===1))continue;for(let i=1;i<f.pts.length-1;i++)this.raster([f.pts[0],f.pts[i],f.pts[i+1]],[f.z[0],f.z[i],f.z[i+1]],f.rgb,f.alpha);}
 for(let label of this.textMeshes){if(TR.V.len(TR.V.sub(label.p,this.eye))>370)continue;let p=label.corners.map(p=>this.camera(p));if(p.some(p=>p[2]<.2))continue;let pts=p.map(q=>this.screen(q)),z=p.map(q=>1/q[2]);this.raster(pts.slice(0,3),z.slice(0,3),[255,255,255],1,{pixels:label.pixels,uv:[[0,127],[511,127],[511,0]]});this.raster([pts[0],pts[2],pts[3]],[z[0],z[2],z[3]],[255,255,255],1,{pixels:label.pixels,uv:[[0,127],[511,0],[0,0]]});}
 ctx.putImageData(image,0,0);
 }
 raster(p,z,rgb,alpha,tex=null){
 let width=this.canvas.width,height=this.canvas.height,x0=p[0][0],y0=p[0][1],x1=p[1][0],y1=p[1][1],x2=p[2][0],y2=p[2][1];let minX=Math.max(0,Math.floor(Math.min(x0,x1,x2))),maxX=Math.min(width-1,Math.ceil(Math.max(x0,x1,x2))),minY=Math.max(0,Math.floor(Math.min(y0,y1,y2))),maxY=Math.min(height-1,Math.ceil(Math.max(y0,y1,y2)));if(minX>maxX||minY>maxY)return;let den=(y1-y2)*(x0-x2)+(x2-x1)*(y0-y2);if(Math.abs(den)<.01)return;let ax=(y1-y2)/den,ay=(x2-x1)/den,bx=(y2-y0)/den,by=(x0-x2)/den,ar=((y1-y2)*(minX+.5-x2)+(x2-x1)*(minY+.5-y2))/den,br=((y2-y0)*(minX+.5-x2)+(x0-x2)*(minY+.5-y2))/den;
 let col=(255<<24)|(rgb[2]<<16)|(rgb[1]<<8)|rgb[0],pixels=this.pixels,out=this.p32,depth=this.depthBuffer,iz0=z[0],iz1=z[1],iz2=z[2];for(let y=minY;y<=maxY;y++){let a=ar,b=br,idx=y*width+minX;for(let x=minX;x<=maxX;x++,idx++,a+=ax,b+=bx){let cc=1-a-b;if(a<-.0001||b<-.0001||cc<-.0001)continue;let iz=a*iz0+b*iz1+cc*iz2;if(iz+1e-7<depth[idx])continue;if(tex){let uv=tex.uv,u=TR.clamp(Math.round((a*uv[0][0]*iz0+b*uv[1][0]*iz1+cc*uv[2][0]*iz2)/iz),0,511),v=TR.clamp(Math.round((a*uv[0][1]*iz0+b*uv[1][1]*iz1+cc*uv[2][1]*iz2)/iz),0,127),ti=(v*512+u)*4,d=tex.pixels;if(d[ti+3]<40)continue;out[idx]=(255<<24)|(d[ti+2]<<16)|(d[ti+1]<<8)|d[ti];depth[idx]=iz;}else if(alpha<.99){let i=idx*4;pixels[i]=pixels[i]*(1-alpha)+rgb[0]*alpha;pixels[i+1]=pixels[i+1]*(1-alpha)+rgb[1]*alpha;pixels[i+2]=pixels[i+2]*(1-alpha)+rgb[2]*alpha;}else{out[idx]=col;depth[idx]=iz;}}ar+=ay;br+=by;}
 }
 texTri(img,uv,p){let c=this.ctx;let x0=uv[0][0],y0=uv[0][1],x1=uv[1][0],y1=uv[1][1],x2=uv[2][0],y2=uv[2][1],den=x0*(y1-y2)+x1*(y2-y0)+x2*(y0-y1);if(!den)return;const co=k=>[(p[0][k]*(y1-y2)+p[1][k]*(y2-y0)+p[2][k]*(y0-y1))/den,(p[0][k]*(x2-x1)+p[1][k]*(x0-x2)+p[2][k]*(x1-x0))/den,(p[0][k]*(x1*y2-x2*y1)+p[1][k]*(x2*y0-x0*y2)+p[2][k]*(x0*y1-x1*y0))/den];let a=co(0),b=co(1);c.save();c.globalAlpha=1;c.beginPath();c.moveTo(...p[0]);c.lineTo(...p[1]);c.lineTo(...p[2]);c.closePath();c.clip();c.setTransform(a[0],b[0],a[1],b[1],a[2],b[2]);c.drawImage(img,0,0);c.restore();}
};
