/* Deterministic simulation. Metres, seconds and metres/second internally. */
TR.CARS={gt:{name:'Lakeside GT',tag:'THE ALL-ROUNDER',max:57,accel:15,handling:1,boost:77,color:'#d8f76b'},rally:{name:'Yeoor Rally',tag:'GRIP FOR THE GHATS',max:53,accel:17,handling:1.30,boost:73,color:'#efa76e'},auto:{name:'Rickshaw Rocket',tag:'THREE WHEELS. ZERO CHILL.',max:46,accel:18,handling:1.12,boost:78,color:'#f1cd64'}};
TR.Simulation=class{
 constructor(route,onEvent=()=>{}){this.route=route;this.onEvent=onEvent;this.state='menu';this.reset('rush','gt');this.state='menu';}
 emit(type,data={}){this.onEvent({type,...data});}
 reset(mode='rush',car='gt'){this.mode=mode;this.car=car;this.spec=TR.CARS[car];this.state='countdown';this.countdown=3.15;this.countNumber=4;this.s=0;this.x=-1.65;this.vx=0;this.speed=0;this.nitro=100;this.nitroLock=0;this.time=0;this.remaining=mode==='monsoon'?46:40;this.score=0;this.nearMisses=0;this.pickups=0;this.collisions=0;this.topSpeed=0;this.driftTime=0;this.combo=1;this.comboTime=0;this.zone=0;this.lap=0;this.cooldown=0;this.hornCooldown=0;this.hornPulse=0;this.boosting=false;this.drifting=false;this.finished=false;this.lastCollisionSector=0;this.lastCheckpoint=0;this.shake=0;this.offroad=false;this.visualTime=0;this.result=null;this.rng=TR.rng(mode==='monsoon'?4097:4004);this.traffic=[];this.items=[];this.hazards=[];this.rivals=[];
 let lanes=[-5.15,-1.75,1.75,5.15],total=mode==='free'?30:mode==='monsoon'?66:49;
 for(let i=0;i<total;i++){let s=110+i*(this.route.length-140)/total+(this.rng()-.5)*24,kind=i%11===5?'bus':i%3===0?'auto':'traffic',x=lanes[i%4];if(this.route.width(s)<12)x=TR.clamp(x,-4,4);this.traffic.push({s,x,targetX:x,lane:x,kind,speed:(kind==='bus'?15:kind==='auto'?20:24)+this.rng()*9,passed:false,phase:this.rng()*6.283,width:kind==='bus'?1.3:kind==='auto'?.85:1,length:kind==='bus'?4.1:2.2});}
 for(let i=0;i<3;i++)this.rivals.push({s:9+i*9,x:[-4.8,1.75,4.8][i],speed:0,max:48+i*2.8,kind:'rival'+(i+1),finishedAt:null,phase:i*1.8});
 for(let s=72,i=0;s<this.route.length;s+=93,i++){let x=lanes[(i*3+1)%4];x=TR.clamp(x,-this.route.width(s)/2+1.2,this.route.width(s)/2-1.2);this.items.push({s,x,used:false,phase:this.rng()*6.283});}
 for(let s=170,i=0;s<this.route.length;s+=mode==='monsoon'?79:118,i++){let x=lanes[(i+1)%4]+(this.rng()-.5);x=TR.clamp(x,-4.5,4.5);this.hazards.push({s,x,type:i%5===3?'cone':'pothole',hit:false});}
 this.emit('reset');}
 start(){this.state='running';this.emit('go');}
 pause(){if(this.state==='running'||this.state==='countdown'){this.beforePause=this.state;this.state='paused';this.emit('pause');}}
 resume(){if(this.state==='paused'){this.state=this.beforePause||'running';this.emit('resume');}}
 horn(){if(this.state!=='running'||this.hornCooldown>0)return false;this.hornCooldown=1.6;this.hornPulse=.65;let count=0;for(let v of this.traffic){let d=v.s-this.s;if(d>0&&d<95){v.targetX=(v.x>0?1:-1)*(this.route.width(v.s)/2-.75);count++;}}this.emit('horn',{count});return true;}
 hit(kind){if(this.cooldown>0)return;this.cooldown=1.3;this.collisions++;this.combo=1;this.comboTime=0;this.speed*=kind==='pothole'?.72:.46;this.score=Math.max(0,this.score-(kind==='pothole'?80:180));this.shake=.75;this.emit('hit',{kind});}
 award(points,label){let add=Math.round(points*this.combo*(this.car==='auto'?1.25:1));this.score+=add;this.emit('score',{points:add,label});}
 step(dt,input={}){dt=TR.clamp(dt,0,.05);this.visualTime+=dt;this.shake=Math.max(0,this.shake-dt*1.7);if(this.state==='countdown'){this.countdown-=dt;let n=Math.ceil(this.countdown);if(n!==this.countNumber){this.countNumber=n;if(n>0)this.emit('count',{number:n});}if(this.countdown<=0)this.start();return;}
 if(this.state!=='running')return;this.time+=dt;if(this.mode!=='free')this.remaining-=dt;this.cooldown=Math.max(0,this.cooldown-dt);this.hornCooldown=Math.max(0,this.hornCooldown-dt);this.hornPulse=Math.max(0,this.hornPulse-dt);this.comboTime=Math.max(0,this.comboTime-dt);if(!this.comboTime)this.combo=1;
 const prevS=this.s,wet=this.mode==='monsoon',spec=this.spec,brake=!!input.brake,steer=TR.clamp(Number(input.steer)||0,-1,1),throttle=!!input.throttle;
 this.boosting=!!input.boost&&this.nitro>0&&this.speed>5&&!brake&&!this.nitroLock;
 if(this.boosting){this.nitro=Math.max(0,this.nitro-dt*(this.car==='auto'?22:24));if(this.nitro===0)this.nitroLock=1;}else{this.nitro=Math.min(100,this.nitro+dt*(this.mode==='free'?11:5.5));if(this.nitro>18)this.nitroLock=0;}
 this.drifting=!!input.drift&&Math.abs(steer)>.15&&this.speed>19;
 let top=(this.boosting?spec.boost:spec.max)*(wet?.93:1);if(brake)this.speed=Math.max(0,this.speed-dt*31);else if(throttle||this.boosting)this.speed+=dt*spec.accel*(this.boosting?1.45:Math.max(.06,1-this.speed/top));else this.speed=Math.max(0,this.speed-dt*5.5);
 if(this.boosting)this.speed=Math.min(top,this.speed);else if(this.speed>top)this.speed=Math.max(top,this.speed-dt*15);if(this.drifting)this.speed=Math.max(0,this.speed-dt*2.4);
 let grip=spec.handling*(wet?.80:1),lateral=steer*(3.2+this.speed*.09)*(this.drifting?1.6:1)*grip,bend=this.route.curvature(this.s),centrifugal=-bend*this.speed*this.speed*(this.drifting?.10:.065)/grip;
 this.vx=TR.mix(this.vx,lateral+centrifugal,1-Math.exp(-dt*(this.drifting?2.3:wet?4.3:7.5)));this.x+=this.vx*dt*(this.speed>1?1:this.speed);let edge=this.route.width(this.s)/2-1.0;this.offroad=Math.abs(this.x)>edge;let maxEdge=edge+1.65;
 if(this.offroad){this.speed=Math.max(0,this.speed-dt*18);this.nitro=Math.max(0,this.nitro-dt*3);if(Math.abs(this.x)>maxEdge){this.x=TR.clamp(this.x,-maxEdge,maxEdge);this.vx*=-.1;if(this.speed>12)this.hit('barrier');}}
 this.s+=this.speed*dt;this.topSpeed=Math.max(this.topSpeed,this.speed*3.6);
 if(this.drifting&&!this.offroad){this.driftTime+=dt;this.score+=dt*(8+this.speed*.12);this.nitro=Math.min(100,this.nitro+dt*7);}
 for(let v of this.traffic){let before=v.s-prevS;v.s+=v.speed*dt;v.x=TR.mix(v.x,v.targetX,1-Math.exp(-dt*1.35));if(Math.abs(v.targetX-v.lane)>.1&&this.hornCooldown<.1)v.targetX=v.lane;let d=v.s-this.s;if(d< -130){v.s+=this.route.length;v.passed=false;v.lane=TR.clamp(v.lane,-this.route.width(v.s)/2+1,this.route.width(v.s)/2-1);v.targetX=v.lane;}
 if(Math.abs(d)<v.length+1.55&&Math.abs(this.x-v.x)<v.width+.79)this.hit(v.kind);
 if(!v.passed&&before>=0&&d<0){v.passed=true;let dx=Math.abs(this.x-v.x);if(dx>v.width+.85&&dx<v.width+2.3&&this.speed>v.speed+7&&this.cooldown===0){this.nearMisses++;this.combo=Math.min(5,1+Math.floor(this.nearMisses%8/2));this.comboTime=6;this.award(100,'CLEAN OVERTAKE');}}
 }
 if(this.mode!=='free')for(let v of this.rivals){if(v.finishedAt!==null)continue;let b=Math.abs(this.route.curvature(v.s));let aim=v.max-Math.min(10,b*1400)+Math.sin(this.time*.18+v.phase)*1.6;v.speed=TR.mix(v.speed,aim,1-Math.exp(-dt*.35));v.s+=v.speed*dt;let lane=[-3.5,1.6,3.7][this.rivals.indexOf(v)];v.x=TR.mix(v.x,lane+Math.sin(this.time*.4+v.phase)*.7,dt*.7);if(Math.abs(v.s-this.s)<3.7&&Math.abs(v.x-this.x)<1.75){this.hit('rival');v.speed*=.91;}if(v.s>=this.route.length)v.finishedAt=this.time;}
 for(let item of this.items){let s=item.s+this.lap*this.route.length;if(!item.used&&Math.abs(s-this.s)<2.4&&Math.abs(item.x-this.x)<1.28){item.used=true;this.pickups++;this.nitro=Math.min(100,this.nitro+35);this.nitroLock=0;this.award(250,'CHAI CHARGE');this.emit('pickup');}}
 for(let h of this.hazards){let s=h.s+this.lap*this.route.length;if(!h.hit&&Math.abs(s-this.s)<2.1&&Math.abs(h.x-this.x)<(h.type==='cone'?.9:1.1)){h.hit=true;this.hit(h.type);}}
 let lap=Math.floor(this.s/this.route.length),zi=this.route.zone(this.s);if(zi!==this.zone){let old=this.zone;this.zone=zi;if(zi>old){this.remaining+=this.mode==='monsoon'?25:23;let clean=this.collisions===this.lastCollisionSector;this.lastCollisionSector=this.collisions;this.score+=clean?500:200;this.lastCheckpoint=this.time;this.emit('checkpoint',{zone:zi,clean,seconds:this.mode==='monsoon'?25:23});}}
 if(this.s>=this.route.length&&this.mode!=='free'){this.finish(true);return;}if(lap>this.lap&&this.mode==='free'){this.lap=lap;for(let i of this.items)i.used=false;for(let h of this.hazards)h.hit=false;this.emit('lap',{lap:lap+1});}
 if(this.mode!=='free'&&this.remaining<=0){this.remaining=0;this.finish(false);}
 }
 position(){return this.mode==='free'?1:1+this.rivals.filter(v=>v.s>this.s||v.finishedAt!==null).length;}
 finish(completed=true){if(this.state==='results')return;this.state='results';this.finished=completed;let pos=this.position(),distance=Math.min(this.s,this.mode==='free'?this.s:this.route.length),bonus=completed&&this.mode!=='free'?5000+Math.round(this.remaining*25)+(4-pos)*500:0,score=Math.floor(this.score)+bonus;this.result={mode:this.mode,car:this.car,completed,score,time:this.time,distance,position:pos,collisions:this.collisions,nearMisses:this.nearMisses,pickups:this.pickups,topSpeed:Math.round(this.topSpeed),drift:Math.round(this.driftTime),bonus,date:new Date().toISOString(),medal:this.mode==='free'?'EXPLORER':!completed?'ONE MORE RUN':pos===1&&this.collisions<7?'GOLD':pos<=2?'SILVER':'BRONZE'};this.emit('finish',{result:this.result});}
};
TR.Audio=class{
 constructor(){this.ctx=null;this.enabled=true;this.music=false;this.nextBeat=0;this.beat=0;}
 init(){if(this.ctx){this.ctx.resume().catch(()=>{});return;}try{let A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.34;this.master.connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=230;this.gain=this.ctx.createGain();this.gain.gain.value=0;this.engine.connect(this.filter);this.filter.connect(this.gain);this.gain.connect(this.master);this.engine.start();}catch(e){this.enabled=false;}}
 tone(f,d=.15,type='sine',volume=.13,slide=0){if(!this.ctx||!this.enabled)return;let t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,f+slide),t+d);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d+.02);}
 event(type){if(type==='count')this.tone(440,.1,'sine',.14);if(type==='go'){this.tone(880,.35,'sine',.21);setTimeout(()=>this.tone(1320,.2,'sine',.12),90);}if(type==='horn'){this.tone(330,.30,'sawtooth',.10);this.tone(415,.30,'sawtooth',.09);}if(type==='pickup'){this.tone(660,.19,'sine',.14,400);setTimeout(()=>this.tone(1046,.2,'sine',.11),80);}if(type==='checkpoint'){this.tone(523,.28,'triangle',.15);setTimeout(()=>this.tone(784,.3,'triangle',.15),130);}if(type==='hit'){this.tone(90,.27,'sawtooth',.22,-65);}if(type==='finish'){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>this.tone(f,.45,'triangle',.12),i*130));}}
 update(g){if(!this.ctx)return;let active=g.state==='running'&&this.enabled,t=this.ctx.currentTime;this.gain.gain.setTargetAtTime(active?.06+g.speed*.0012:0,t,.07);this.engine.frequency.setTargetAtTime(36+g.speed*1.5+(g.speed%14)*2,t,.05);this.filter.frequency.setTargetAtTime(160+g.speed*10,t,.06);if(active&&this.music&&t>=this.nextBeat){let notes=[130.81,164.81,196,261.63,146.83,174.61,220,293.66];this.tone(notes[this.beat%8],.28,'triangle',.075);if(this.beat%2===0)this.tone(64,.14,'sine',.17,-30);if(this.beat%4===2)this.tone(190,.08,'triangle',.06,120);this.beat++;this.nextBeat=t+.24;}}
};
TR.Store={key:'thane-rush-v1',load(){try{let x=JSON.parse(localStorage.getItem(this.key)||'{}');if(!x||typeof x!=='object'||Array.isArray(x))return{scores:[],settings:{}};return{scores:Array.isArray(x.scores)?x.scores.filter(r=>r&&typeof r.score==='number'&&Number.isFinite(r.score)).slice(0,30):[],settings:x.settings&&typeof x.settings==='object'?x.settings:{}};}catch(e){return{scores:[],settings:{}};}},save(data){try{localStorage.setItem(this.key,JSON.stringify(data));return true;}catch(e){return false;}}};
