/* Run with: node tests/simulation.test.js. No npm dependencies. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),mem=new Map(),context={console,Math,Date,Float32Array,Uint32Array,setTimeout,localStorage:{getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v)}};
vm.createContext(context);vm.runInContext(['engine.js','world.js','game.js'].map(f=>fs.readFileSync(path.join(root,'src',f),'utf8')).join('\n')+'\nglobalThis.GameAPI=TR;',context);const TR=context.GameAPI;let passed=0;const report=[];
function test(name,fn){try{fn();passed++;report.push({name,passed:true});console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;report.push({name,passed:false,error:e.message});}}
function sim(mode='rush',car='gt'){const events=[],g=new TR.Simulation(new TR.Route(),e=>events.push(e));g.reset(mode,car);g.start();return{g,events};}
function step(g,t,input={throttle:true}){for(let i=0;i<t*120;i++)g.step(1/120,input);}
function empty(g){g.traffic=[];g.rivals=[];g.items=[];g.hazards=[];}
test('Closed course is 5.069 km and has six named sectors',()=>{let r=new TR.Route();assert.ok(r.length>5050&&r.length<5080);assert.equal(r.zones.length,6);assert.ok(TR.V.len(TR.V.sub(r.point(0),r.point(r.length)))<1e-9);});
test('Every road frame is finite, normalized and orthogonal',()=>{let r=new TR.Route();for(let s=0;s<r.length;s+=13){let f=r.frame(s);assert.ok([...f.p,...f.t,...f.r,f.yaw,f.pitch].every(Number.isFinite));assert.ok(Math.abs(TR.V.dot(f.r,f.t))<1e-8);assert.ok(Math.abs(TR.V.len(f.t)-1)<1e-8);assert.ok(r.width(s)>=11);}});
test('Countdown starts a real run and emits GO',()=>{let {g,events}=sim();g.reset();step(g,3.2);assert.equal(g.state,'running');assert.ok(events.some(e=>e.type==='go'));});
test('Acceleration raises speed without exceeding the base maximum',()=>{let {g}=sim();empty(g);step(g,9);assert.ok(g.speed>48&&g.speed<=57);assert.ok(g.s>250);});
test('Right and left steering move the car in the correct directions',()=>{let {g}=sim();empty(g);g.speed=35;let x=g.x;step(g,.35,{throttle:true,steer:1});assert.ok(g.x>x);let y=g.x;step(g,.65,{throttle:true,steer:-1});assert.ok(g.x<y);});
test('Brake stops the car; it never reverses',()=>{let {g}=sim();empty(g);g.speed=45;step(g,3,{brake:true});assert.equal(g.speed,0);assert.ok(g.s>=0);});
test('Nitro is consumed and increases achievable speed',()=>{let {g}=sim();empty(g);g.speed=50;step(g,2,{throttle:true,boost:true});assert.ok(g.nitro<55);assert.ok(g.speed>57);});
test('Sustained boost never exceeds the vehicle ceiling in either weather',()=>{for(let mode of ['rush','monsoon'])for(let car of ['gt','rally','auto']){let {g}=sim(mode,car);empty(g);g.speed=g.spec.max;for(let i=0;i<720;i++){g.nitro=100;g.step(1/120,{throttle:true,boost:true});assert.ok(g.speed<=g.spec.boost*(mode==='monsoon'?.93:1)+1e-6);}}});
test('Releasing boost slows smoothly toward the normal speed ceiling',()=>{let {g}=sim();empty(g);g.speed=75;g.step(1/120,{throttle:true});assert.ok(g.speed>74&&g.speed<75);step(g,3);assert.ok(g.speed<=g.spec.max+.01);});
test('Empty nitro has a recharge lock rather than flickering boost',()=>{let {g}=sim();empty(g);g.speed=55;g.nitro=.1;step(g,.1,{throttle:true,boost:true});assert.equal(g.nitroLock,1);assert.equal(g.boosting,false);step(g,4);assert.equal(g.nitroLock,0);});
test('Drifting needs speed plus steering and regenerates nitro',()=>{let {g}=sim();empty(g);g.speed=35;g.nitro=20;step(g,.3,{throttle:true,steer:.4,drift:true});assert.ok(g.driftTime>0);assert.ok(g.nitro>23);});
test('Horn moves traffic toward the shoulder and obeys cooldown',()=>{let {g}=sim();g.traffic=[{s:40,x:1.75,targetX:1.75,lane:1.75,speed:20,kind:'auto',width:.85,length:2.2}];assert.equal(g.horn(),true);assert.ok(g.traffic[0].targetX>5);assert.equal(g.horn(),false);});
test('Contacts deduct points once during the recovery cooldown',()=>{let {g}=sim();empty(g);g.score=1000;g.speed=45;g.hit('bus');assert.equal(g.score,820);assert.equal(g.collisions,1);g.hit('bus');assert.equal(g.collisions,1);assert.ok(g.speed<23);});
test('Potholes cost 80 points',()=>{let {g}=sim();empty(g);g.score=1000;g.hit('pothole');assert.equal(g.score,920);});
test('Chai pickups award points and refill nitro exactly once',()=>{let {g}=sim();empty(g);g.nitro=40;g.items=[{s:0,x:g.x,used:false}];g.step(.01,{});assert.equal(g.pickups,1);assert.ok(g.nitro>=75);assert.equal(g.score,250);g.step(.01,{});assert.equal(g.pickups,1);});
test('Rickshaw pickup rewards have the promised 25% bonus',()=>{let {g}=sim('rush','auto');empty(g);g.items=[{s:0,x:g.x,used:false}];g.step(.01,{});assert.equal(g.score,313);});
test('Close clean overtakes score, without rewarding collisions',()=>{let {g}=sim();empty(g);g.speed=50;g.x=0;g.traffic=[{s:.2,x:2.8,targetX:2.8,lane:2.8,speed:20,kind:'traffic',width:1,length:2.2,passed:false}];g.step(.02,{throttle:true});assert.equal(g.nearMisses,1);assert.equal(g.collisions,0);assert.equal(g.score,100);});
test('Clean checkpoint adds 23 seconds and 500 points',()=>{let {g}=sim();empty(g);g.s=g.route.length*.13-.1;g.speed=40;g.step(.02,{throttle:true});assert.equal(g.zone,1);assert.ok(g.remaining>62.9);assert.equal(g.score,500);});
test('Pause freezes race time, movement and countdown',()=>{let {g}=sim();empty(g);g.speed=40;g.pause();let s=g.s,t=g.time;step(g,4);assert.equal(g.s,s);assert.equal(g.time,t);g.resume();step(g,.1);assert.ok(g.s>s);});
test('Timeout produces an incomplete result, not a false finish',()=>{let {g}=sim();empty(g);g.remaining=.01;g.step(.02,{});assert.equal(g.state,'results');assert.equal(g.result.completed,false);assert.equal(g.result.bonus,0);});
test('Crossing the finish produces completion, rank and bonus',()=>{let {g}=sim();empty(g);g.s=g.route.length-.2;g.zone=5;g.speed=35;g.step(.02,{throttle:true});assert.equal(g.state,'results');assert.equal(g.result.completed,true);assert.ok(g.result.bonus>=5000);assert.equal(g.result.position,1);});
test('Sunday drive loops indefinitely and resets lap pickups',()=>{let {g}=sim('free');empty(g);g.s=g.route.length-.1;g.zone=5;g.speed=40;g.items=[{s:72,x:1,used:true}];g.step(.02,{throttle:true});assert.equal(g.state,'running');assert.equal(g.lap,1);assert.equal(g.items[0].used,false);assert.ok(g.s>g.route.length);});
test('Monsoon has more traffic and a lower-grip speed ceiling',()=>{let a=sim('rush').g,b=sim('monsoon').g;assert.ok(b.traffic.length>a.traffic.length);empty(a);empty(b);step(a,10);step(b,10);assert.ok(b.speed<a.speed);});
test('Seeded restart reproduces traffic placement',()=>{let {g}=sim();let before=JSON.stringify(g.traffic);g.reset('rush','gt');assert.equal(JSON.stringify(g.traffic),before);});
test('Missing and corrupt saved data are handled safely',()=>{mem.clear();assert.equal(TR.Store.load().scores.length,0);mem.set(TR.Store.key,'not json');assert.equal(TR.Store.load().scores.length,0);mem.set(TR.Store.key,'null');assert.equal(TR.Store.load().scores.length,0);});
test('Storage save/load round-trips records and settings',()=>{mem.clear();let data={scores:[{score:123,car:'gt',mode:'rush'}],settings:{auto:false}};assert.equal(TR.Store.save(data),true);assert.equal(TR.Store.load().scores[0].score,123);assert.equal(TR.Store.load().settings.auto,false);});
// A complete, unmodified race controlled by a simple test driver (no teleports).
function driveRace(mode,car){let {g}=sim(mode,car),dt=1/60;while(g.state==='running'&&g.time<240){let candidates=[-4.3,-1.65,1.65,4.3].map(x=>TR.clamp(x,-g.route.width(g.s)/2+1.2,g.route.width(g.s)/2-1.2)),target=g.x,best=Infinity;for(let x of candidates){let cost=Math.abs(x-g.x)*.3;for(let v of [...g.traffic,...g.rivals]){let ds=v.s-g.s;if(ds>-6&&ds<65&&Math.abs(v.x-x)<2.15)cost+=30/(Math.max(0,ds)+6);}for(let h of g.hazards){let ds=h.s-g.s;if(!h.hit&&ds>0&&ds<45&&Math.abs(h.x-x)<1.3)cost+=14/(ds+5);}if(cost<best){best=cost;target=x;}}let curvature=g.route.curvature(g.s),grip=g.spec.handling*(mode==='monsoon'?.8:1),desiredVX=TR.clamp((target-g.x)*2.7,-7,7),centrifugal=-curvature*g.speed*g.speed*.065/grip,steer=TR.clamp((desiredVX-centrifugal)/((3.2+g.speed*.09)*grip),-1,1);g.step(dt,{throttle:true,steer,boost:g.nitro>20&&best<.65&&Math.abs(curvature)<.0035});if(g.hornCooldown===0)g.horn();}return g.result;}
const runs=[];
test('Full sunset race completes using only normal driving inputs',()=>{let r=driveRace('rush','gt');assert.ok(r?.completed);assert.ok(r.time<170);runs.push(r);console.log('  Full run:',JSON.stringify(r));});
test('Full wet-road race is completable with the rally car',()=>{let r=driveRace('monsoon','rally');assert.ok(r?.completed);runs.push(r);console.log('  Full run:',JSON.stringify(r));});
fs.writeFileSync(path.join(root,'tests','simulation-results.json'),JSON.stringify({passed,total:report.length,tests:report,fullRuns:runs},null,2));console.log(`\n${passed}/${report.length} tests passed.`);
